### ISSUE TITLE
Don't open the cropping UI when a new image is selected in Free Crop mode or when the image is already the correct ratio in Aspect Ratio or Pixel Size mode

### ISSUE THREAD

**Issue by gavin310** [joppuyo/acf-image-aspect-ratio-crop#109]
We'd like our users to use this field for all their image cropping (in most cases) instead of using WordPress' confusing cropping process. The issue is with how the cropping UI always shows up whenever a new image is selected. In Free Crop mode, cropping should be optional, so it would be nice to have an option to not show the cropping UI when a new image is selected. Then in Aspect Ratio or Pixel Size modes, I uploaded an image that was already sized to the correct size, but the cropping UI still shows up. Is it possible to have the UI not show in the cases where cropping isn't necessary?

**Comment by joppuyo** [comment]
Hello. I'm currently working on rewriting the plugin so I don't plan on adding any new features until the new version has been released. But here are my comments on these suggestions.

Optional cropping in free crop mode

If you don't want to crop the image, can't you just select the whole image as a crop target? I don't really want to make the cropping optional because the idea of the plugin is that the image size is always defined. Adding this feature would complicate the plugin logic so I need to consider it thoroughly before potentially implementing the feature

No crop if the image size matches

Sometimes the user might want to select a part of the image despite the aspect ratio already being correct so I don't want to take away this feature. There's already a logic that skips the cropping if the aspect ratio matches the image and the crop area is the whole image. In this case the plugin just uses the original image instead of creating a new identical one.

**Comment by joppuyo** [comment]
I'm going to close this issue since there features are not currently planned to be included in the plugin as I explained in the previous message.
