### ISSUE TITLE
Huge image gets corrupted

### ISSUE THREAD

**Issue by aceArt-GmbH** [joppuyo/acf-image-aspect-ratio-crop#136]
Hey, thanks for maintaining this plugin :)

We are currently facing an issue with the cropping of huge images.
When editing a huge image (22MB 25192 x 14175px) and cropping to a somewhat big size the resulting image is black & white and not the selected area

Input image https://hff-screenings.de/wp-content/uploads/2024/02/Stimmungsbild_whereweusedtosleep.png
Output image https://hff-screenings.de/wp-content/uploads/2024/02/Stimmungsbild_whereweusedtosleep-aspect-ratio-2524-1420.png

Cropping the image to a very small part of the original seems to work just fine.

(Aspect ratio 2506x3402)

Debug log does not print anything.
Do you have any idea what the problem might be?

Version 6.0.3
Wordpress 6.4.3
PHP 8.3.3
ImageMagick 6.9.11

**Comment by joppuyo** [comment]
Hello! It's very likely that the issue is not with this plugin: it simply uses the underlying image editing functionality that WordPress provides. Because the image is so large, the ImageMagick or GD library WordPress uses might be running out of memory which corrupts the image. I recommend uploading a smaller version of the image to prevent this issue from happening.

**Comment by aceArt-GmbH** [comment]
I'd still know which part is failing, but you are right.
It's probably not a problem with this extension.

Thanks for your input on this
