### ISSUE TITLE
Delete previous cropped image when new crop is performed

### ISSUE THREAD

**Issue by joppuyo** [joppuyo/acf-image-aspect-ratio-crop#4]
* This should probably be done on post save so we don't break any links

**Comment by gaambo** [comment]
hi there, 
i thought about this too - right now the cropped image is created in all registered image sizes. when i use the same image in another field and crop it to the same format it is also resaved. also when removing the image and adding it again and choosing the same cropping area (the default centered one).

so this leads to a lot of files - a part of the problem is how wordpress generates all image sizes upfront. 
my ideas: 

- save the selected coordinates as meta information so we can check if we already cropped the same image with the same coordinates and take this instead
- delete old images when recropping (=other coordinates)
- maybe do not generate all image sizes or let the developer/user choose via a setting in the field.

what do you think about that? would be glad to help!

**Comment by joppuyo** [comment]
Hey, thanks for reaching out and for your thoughtful message.

By the looks of it, there are actually 3 different issues.

* Let's start with the image sizes: This is by design, my main use case is to generate responsive variants for the images using srcset in a set aspect ratio. This is the main reason I wrote this plugin since [ACF image crop](https://wordpress.org/plugins/acf-image-crop-add-on/) does not support aspect ratio, only a pixel size. The aforementioned plugin also offers possibility to only generate single image. If there are use cases for single image support, I think it would be worth adding to this plugin too.
* Saving coordinates in post meta and not generating image if it already exists: This is a good idea and we'd need to save that data in any case if we want to implement #2 : Show current crop when re-cropping image
* Abandoned images: Meaning cropped images that are not used in any post because they are re-cropped or deleted from a post. For this, we'd need to do something like [Media Cleaner](https://wordpress.org/plugins/media-cleaner/) does, it scans for media files that are not referenced in any post and deletes them. They have some ACF specific code in the plugin, [here](https://wordpress.org/plugins/media-cleaner/). This should not probably be run while to user is working on the site but rather as cron or as a [background process](https://github.com/A5hleyRich/wp-background-processing)

I'm probably not able to work on any of these issues right away, but pull requests are always welcome. Just ping me if you start working on something so we don't accidentally write the code twice.

**Comment by joppuyo** [comment]
I think for number 3, we could execute the code on post save and get all acf-image-aspect-ratio-crop meta fields for the current post. If some of them are not used (they do not exists or are part of a old revision), then delete them. This would be less resource intensive than scanning the whole site.

**Comment by joppuyo** [comment]
Need to also handle deleting abandoned images on post delete

**Comment by joppuyo** [comment]
This feature is not available in the latest version v3.1.8 as a beta.

You can find it in the Plugins -> ACF Image Aspect Ratio Crop -> Settings
