### ISSUE TITLE
Move settings to options-media.php

### ISSUE THREAD

**Issue by 1ucay** [joppuyo/acf-image-aspect-ratio-crop#41]
Hi, can you move setting of ACF Crop to Media 
https://ibd.refreshpixel.com/admin/options-media.php
instead of
options-general.php?page=acf-image-aspect-ratio-crop

Many plugin related to Media add setting subpage, but I think it is better to add to options-media.php.

**Comment by joppuyo** [comment]
Hey,

I don't think a plugin for Advanced Custom Fields should add any options to core WordPress media options pages since these two things aren't really related.

I know some plugins do extend core options pages but it's rare and at least for me, it's the least likely place I would search for them.

I'm pretty happy about where the options are located right now. Besides, there isn't even an item for the plugin in the options submenu, the only way to access the options page is from the plugin list.
