### ISSUE TITLE
Disable forced cropping

### ISSUE THREAD

**Issue by web-chaos** [joppuyo/acf-image-aspect-ratio-crop#94]
Disable forced cropping on the first or any adding of a photo. Need to be able to control the cropping of the photo at will. I added a photo through this field and saved it without cropping it. If after saving the photo I need a crop, then I click on the crop icon and crop.

**Comment by joppuyo** [comment]
Could you tell me the use case for this feature? I think an image field either needs to be in a certain aspect ratio or not.

If your image doesn't need to be in a specific aspect ratio, you can use the native ACF image field.

If you want the user to be able to crop the image to an arbitrary aspect ratio, you can use the free crop feature in the plugin.

**Comment by web-chaos** [comment]
In fact of the matter. I do not need to crop all photos manually. Most of my photos are cropped in the standard way through add_image_size.
Let's say I have a photo field for an arbitrary block or post. This field is used in every post. But there are times when I need to crop a photo in this field in my own way, even before it is displayed on the front. And if I switch the field type in the plugin, then I can crop. But doing this every time is not convenient.

I propose to make it so that in your version everything remains as it is, only the photo could be cropped by clicking on the icon, calling the corresponding modal window, and not by force when adding it.

**Comment by joppuyo** [comment]
I made this field because sometimes you have a website layout where elements are specific aspect ratio, for example, an article list has square images.

You could use add_image_size and add a new square image size but that means the image will be automatically cropped and sometimes that doesn't look good.

So I made a field where the content editor has to manually crop the image so it looks good.

If I made the cropping optional it would defeat the whole purpose of the plugin if the user could just decide they don't want to crop the image.

> But there are times when I need to crop a photo in this field in my own way, even before it is displayed on the front.

> But if at some point in this field I need to crop a photo, I will click on the icon in the photo and do it.

I'm sorry but I can't really understand this part. Why do you want to crop the image sometimes but not other times?

I don't want to add a feature to the plugin if I don't see any case where such a feature would be useful. Every feature added to the plugin is something that needs to be tested and maintained from that point on.

I would prefer if we could find some other way to solve this issue. But I can't really come up with anything unless I understand what you are trying to do here.

**Comment by joppuyo** [comment]
Hey, I'm closing this issue since I don't think this feature will fit the spirit of the plugin.

I want to keep the plugin as small and focused as possible so I don't want to add any additional features unless I feel like they should be an integral part of the plugin.

It's unfortunate that the plugin doesn't fit your specific use case but I hope you can find some alternate way to implement your requirements.
